services:
    app.command_handler.bank_account.create:
        class: App\Command\CreateHandler
        arguments:
            - '@app.bank_account.repository'
        tags:
            - { name: tactician.handler, typehints: true }

    app.command_handler.bank_account.assign_account_number:
        class: App\Command\AssignAccountNumberHandler
        arguments:
            - '@app.bank_account.repository'
            - '@app.bank_account.account_number_distributor'
        tags:
            - { name: tactician.handler, typehints: true }

    app.command_handler.bank_account.deposit:
        class: App\Command\DepositHandler
        arguments:
            - '@app.bank_account.repository'
        tags:
            - { name: tactician.handler, typehints: true }

    app.command_handler.bank_account.withdraw:
        class: App\Command\WithdrawHandler
        arguments:
            - '@app.bank_account.repository'
        tags:
            - { name: tactician.handler, typehints: true }
