services:
    App\Consumer\TransactionSocketConsumer:
        arguments:
            - '@http_client'
            - '@logger'
            - '@App\Repository\TransactionRepository'
            - '%env(resolve:APP_TRANSACTIONS_SOCKET)%'

    App\Component\EventSource\DebugSocketConsumer:
        arguments:
            - '@http_client'
            - '@logger'
            - '@app.message_serializer'
            - '%env(resolve:APP_TRANSACTIONS_SOCKET)%'
