version: '3.7'
services:
    db:
        image: mysql:5.7
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sauce
            MYSQL_USER: sauce
            MYSQL_PASSWORD: sauce
    node:
        image: node:17
        working_dir: "/application"
        command: "bin/run_socket"
        volumes:
            - ./:/application
        ports:
            - "3000:3000"
    php:
        build: ./docker/php-fpm
        volumes:
            - ./:/application
        links:
            - db
    nginx:
        image: nginx
        ports:
            - "${HTTP_PORT}:80"
        links:
            - php
        volumes:
            - ./:/application
            - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf
