services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]

    app.message_serializer:
        class: EventSauce\EventSourcing\Serialization\ConstructingMessageSerializer

    app.bank_account.dispatcher:
        class: EventSauce\EventSourcing\SynchronousMessageDispatcher

    app.bank_account.filesystem_repository:
        class: App\Repository\FileSystemRepository
        arguments:
            - '@app.message_serializer'
            - 'bank_account'
            - '%kernel.project_dir%/var/storage'

    app.bank_account.repository:
        class: EventSauce\EventSourcing\ConstructingAggregateRootRepository
        arguments:
            - App\Entity\BankAccount
            - '@app.bank_account.filesystem_repository'
            - '@app.bank_account.dispatcher'

    App\Controller\AccountController:
        arguments:
            - '@app.bank_account.repository'
